### ISSUE TITLE
add mpv as a media player option over vlc

### ISSUE THREAD

**Issue by thejacer87** [tarkah/lazystream#27]
one HUUUGE advantage mpv has is you can scrub to any point in the stream (ie for games that are finished, you can jump straight to the 3rd period)

**Comment by tarkah** [comment]
Nice! I'm out of town this weekend, but I'll try to add this first thing next week.

**Comment by tarkah** [comment]
@thejacer87 I'll be merging this shortly. Since Streamlink supports more than just mpv & vlc, I added an option under the `play` subcommand called `--custom-player <PATH>`. So for mpv, you could specify `--custom-player /usr/bin/mpv`. And playback seeking works with it, awesome! 

See working here:

![Code_2020-03-02_09-58-43](https://user-images.githubusercontent.com/10239377/75703751-f089af80-5c6c-11ea-93f6-d8f347227d4c.png)

**Comment by tarkah** [comment]
New binary should be available shortly:

https://github.com/tarkah/lazystream/releases/tag/v1.9.7

**Comment by thejacer87** [comment]
awesome, will take a look later when im home

**Comment by tarkah** [comment]
@fartyg heads up, you should use `mpv` which you can now pass to as it supports playback seeking!

**Comment by fartyg** [comment]
@tarkah Seems to work great with mpv. Can search through the stream (vod in this case because game already played) like it was a local file. As always thanks for your work here. This is my favorite terminal program. I was thinking that it would be really cool to make a terminal gui with ncurses for it. If I get time I might look into how one would go about doing that :)

edit: I shouldnt say "like it was a local file" becaue I can only seek through what I have already buffered. But still super nice. I suppose I can use --offset to tell it from where it should start buffer.

**Comment by tarkah** [comment]
@fartyg Great to hear! Check out the app I just created, https://github.com/tarkah/tickrs. It's built using TUI-rs and was surprisingly easy to get working. I'd be interested in hearing your thoughts on how a TUI / ncurses like interface could work here!

**Comment by fartyg** [comment]
That looks sick, will check it out when I am home from work!
