### ISSUE TITLE
Add Option to pick stream quality

### ISSUE THREAD

**Issue by schwyl** [tarkah/lazystream#3]
Would be an enhancement if you could specify the actual stream ei: 720p60 or just 720p or just 480p

**Comment by tarkah** [comment]
So I just tested this manually, if I specify the direct link to the m3u8 of the desired resolution instead of the master file, it uses that and stays at that. I assume this lines up with what you are asking?

I'll just need to parse the master and get the respective link. This shouldn't be a problem.

**Comment by schwyl** [comment]
Hehe, man your good, yeah thats all im looking for is the ability to force
which stream it uses. See I want emby to handle the transcoding down to
lower biterates since it is the one server up the media

Cheers

**Comment by tarkah** [comment]
I have this basically working, just trying to correct one small issue.

For some reason a lot of the requests are returning status code 500 when trying to download the master.m3u8 from http://hslive-... ~5-10% of the time it fails and I can't figure out why. I've tried putting a small break between each request (upwards of 1 second between each one) and no dice.

When I use curl to download the file that failed in my program, it downloads no problem. I set the same headers as curl is using... and under the hood my program is also using curl, so I am at a bit of a loss. I don't want to ship this feature until it reliably downloads these files, otherwise it'll cause incomplete output for the m3u / xmltv outputs.

**Comment by schwyl** [comment]
What if you only pull the main m3u8 file and store them in memory then read
them locally?

**Comment by tarkah** [comment]
That's what I am doing, there is no need to make a request on the URL built using the desired quality line, that is just passed back to the user.

It's just that if a day has 35 streams for example... that's 35 master files I have to download, and for some reason 2-4 of those requests are failing with status code 500 or 504. I'm going to build on windows and see if the problem occurs there.

**Comment by tarkah** [comment]
I've published this feature, the issue didn't seem to be occurring on fetching master m3u8 files for the current days or yesterdays games, only a few days back +.  So I think it's acceptable, being it doesn't affect the normal operation of the program when --quality isn't specified.

Test it out in v1.5.0 release and let me know if it works!

**Comment by schwyl** [comment]
Will do

**Comment by schwyl** [comment]
SUCCESS!!!

**Comment by tarkah** [comment]
Sweet! I'll close this out.
