### ISSUE TITLE
Append XML file versus overwriting

### ISSUE THREAD

**Issue by schwyl** [tarkah/lazystream#31]
Would it be possible to have the generated m3u and xml files append instead of over writing so that channel numbers and order stay the same for those of use who are feeding this in to a media player front end like emby.

IE:

Scan runs at 5pm
CH1 Game 1 Feed 1
CH2 Game 1 Feed 2
no other feeds
Scan runs at 6pm
CH1 Game 1 Feed 1
CH2 Game 1 Feed 2
CH3 Game 2 Feed 1
CH4 Game 2 Feed 2
Scan runs at 7pm
CH1 Game 1 Feed 1
CH2 Game 1 Feed 2
CH3 Game 2 Feed 1
CH4 Game 2 Feed 2
CH5 Game 3 Feed 1
CH6 Game 3 Feed 2
CH7 Game 4 Feed 1
CH8 Game 4 Feed 2

**Comment by tarkah** [comment]
Good call! Hmm, I'll need to recognize when a new day is run vs what's in the file so I can delete all records.

**Comment by schwyl** [comment]
You could or just leave it up to the person to run a cron job to delete the files

**Comment by tarkah** [comment]
@schwyl See #37 which I'll merge soon.  I believe this will fix the problem here. I am now creating records for ALL scheduled games for the day, regardless of if the actual stream is available. The order should now remain unchanged since everything is always grabbed.

The programme entries in the XMLTV file also now have the accurate start time, so you should be able to see the "upcoming" games in your TV Guide
