### ISSUE TITLE
Streamlink hls segment key issue

### ISSUE THREAD

**Issue by fartyg** [tarkah/lazystream#39]
Having an issue with Streamlink where it ends streams/recordings at random and sometimes does not start them. Looks to be related to https://github.com/tarkah/lazystream/commit/7d3a61717c1e352efb85759cdcb3185574c1be44

When I use the older versions (of Lazystream) where the output does not start with "Proxying segment key" it works good. Found a similar thing here: https://github.com/NHLGames/NHLGames/issues/228

```
[lazystream][info] Proxying segment key url to: https://xyz
[cli][info] Found matching plugin hls for URL hlsvariant://https://xyz
[cli][info] Available streams: 670k (worst), 1000k, 1450k, 2140k, 2900k, 4100k, 6600k (best)
[cli][info] Opening stream: 6600k (hls)
Exception in thread Thread-HLSStreamWriter:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/site-packages/streamlink/stream/segmented.py", line 167, in run
    self.write(segment, result)
  File "/usr/lib/python3.8/site-packages/streamlink/stream/hls.py", line 140, in write
    self.reader.buffer.write(pkcs7_decode(decrypted_chunk))
  File "/usr/lib/python3.8/site-packages/streamlink/stream/hls.py", line 31, in pkcs7_decode
    raise StreamError("Input is not padded or padding is corrupt, got padding size of {0}".format(val))
streamlink.exceptions.StreamError: Input is not padded or padding is corrupt, got padding size of 60
[cli][error] Try 1/1: Could not open stream <HLSStream('https://xyz.m3u8')>, tried 1 times, exiting
[cli][info] Closing currently open stream...

ERROR: StreamLink failed
```

Kind regards

**Comment by tarkah** [comment]
Thanks for the bug report! I'm testing this right now.

**Comment by tarkah** [comment]
Goddammit, it's because the segment key uri updates eventually. So my technique for swapping out the hostname for IP in the segment key URI doesn't work, because the URI eventually changes and there is no way to have streamlink handle this.

I guess I will have to remove this feature and hosts file updates will still be mandatory until I come around to implementing an actual proxy to handle this

**Comment by tarkah** [comment]
@fartyg Fixed, download new binaries from:

https://github.com/tarkah/lazystream/releases/tag/v1.10.2

I removed binaries from 1.10.0 and 1.10.1 so people don't use those.

I'm going to see if I can submit a PR to streamlink to add a `--hls-segment-key-proxy??` option, which will allow you to pass an IP address and streamlink will dynamically update all new URIs from whatever hostname to that IP. Because having a full fledged proxy seems so wasteful when in reality, all that needs to be done is the hostname -> IP update on that URI.

**Comment by fartyg** [comment]
Confirmed working, thank you!
