### ISSUE TITLE
ERROR: missing field `teamName` at line 1161 column 3

### ISSUE THREAD

**Issue by nexxai** [tarkah/lazystream#41]
Not sure if this is a known issue but getting the above error when just trying to do a basic game select. 
```
➜  lazystream git:(master) ./lazystream select --sport mlb

 |        \   __  /\ \   / ___|__ __|  _ \  ____|    \     \  |
 |       _ \     /  \   /\___ \   |   |   | __|     _ \   |\/ |
 |      ___ \   /      |       |  |   __ <  |      ___ \  |   |
_____|_/    _\____|   _| _____/  _|  _| \_\_____|_/    _\_|  _|


ERROR: missing field `teamName` at line 1161 column 3
```

Any idea what might be going on?

**Comment by tarkah** [comment]
I'll take a look and fix this tomorrow. Thanks for the bug report.

**Comment by nexxai** [comment]
No problem.  If there's anything I can do to help troubleshoot, just let me know.

**Comment by tarkah** [comment]
Thanks! Should be an easy fix. Looks like I'm trying to deserialize a field that doesn't exist in the API response. MLB support didn't haven't a chance to get tested well before COVID hit.

**Comment by tarkah** [comment]
I've fixed this issue and will push out a release shortly. However, it appears the key files for MLB games since last week aren't being hosted on the freegamez.ga proxy server. I've been out of the loop for a couple months, but LazyMan appears to have been shut down. I'd guess they are no longer paying subscription to support MLB games anymore.

Luckily it appears the proxy server is still up, and I can grab NHL games from before March. Fingers crossed that NHL games will be posted once playoffs kick off. I'd think so since it appears https://github.com/NHLGames just pushed out a new release.

**Comment by nexxai** [comment]
Ahhh that makes sense, well thanks for fixing the bug regardless.  Hopefully it works for NHL still going forward.

**Comment by tarkah** [comment]
No problem! Hopefully MLB links are added again in the future.

New release should be posted in ~10min here:

https://github.com/tarkah/lazystream/releases/tag/v1.10.3
