### ISSUE TITLE
Inquiry about XML and M3U

### ISSUE THREAD

**Issue by Evilmnkey** [tarkah/lazystream#44]
Hi,
    First i would like to thank you for this little app that lets me enjoy Hockey without having to use my PC to cast games.
   this is more of an inquiry about how the M3U and XML get exported. Would it be possible to have the playlist export and keep the same channels for games even if the games are done? As an example today i generated a M3U and XML before the Jets and Winnipeg game

The game was set to play on 
#EXTINF:-1 CUID="1000" tvg-id="1000" tvg-name="Lazyman 1",Lazyman 1
but once the game ends it gets pushed down and the current games move up. 

I have a script that exports the XML and M3U from lazystreams every hour ( so i get the link populated to watch the games) so they appear in my IPTV software but since the app refresh of the playlist (Manual) and EPG ( minimum every 2 hours ) is not done in a timely fashion it causes issues of channel and games being out of sync the the wrong games plays with the wrong EPG entry. 

Thanks

**Comment by tarkah** [comment]
Glad you are enjoying the program! Ahh, I can see how that would be annoying. I just looked and confirmed the API returns games in the following order... In Progress -> Scheduled -> Final. Instead, I can sort the games by their game id so it always has the same order.

I'll look at fixing this tomorrow.

**Comment by Evilmnkey** [comment]
Wow thanks for the response, thought this would be a long shot. Will keep and eye out for the changes

**Comment by tarkah** [comment]
I've fixed this with #45. I'll wait to merge until I can validate things stay consistently sorted throughout today. It was a super easy fix, though! Just had to add this line:

```rust
games.sort_by_key(|game| (game.game_date, game.away_team.name.clone()));
```

So I'm first sorting on the game's date / time. If two games are at the same time, then I am sorting on the Away Team's name, since they show up first in the title Away Team @ Home Team.

**Comment by tarkah** [comment]
I've confirmed the sorting is retained. The Islanders / Panthers game ended, which previously would have moved that game to the end, however it is still the first game in the output due to it's start time. The feed orders are all retained as well.

I've published this and the new release is available for download:

https://github.com/tarkah/lazystream/releases/tag/v1.10.4

**Comment by Evilmnkey** [comment]
THanks again. Looking good, will keep checking over the next few games
