### ISSUE TITLE
Not able to play m3u file from past games

### ISSUE THREAD

**Issue by Evilmnkey** [tarkah/lazystream#51]
Hi i am trying to create a m3u file from past games, not sure if its an issue on my end or not. was working fine this summer for the games. 

IE : lazystream.exe --date 20200201 --quality 720p60 generate xmltv
It generates the m3u file and it has the playlist links in it but when itry to load in VLC i get error. 

main error: no suitable access module for `https://mf.svc.nhl.com:443/ws/media/mf/v2.3/key/silk/mediaid/71007003/kid/70290456'
adaptive error: Failed to create demuxer 0000000000000000 Unknown
ps warning: this does not look like an MPEG PS stream, continuing anyway
ps warning: garbage at input from 509, trying to resync...
ps warning: garbage at input from 509, trying to resync...
gnutls error: Certificate verification failure: The certificate is NOT trusted. The certificate chain uses expired certificate. The name in the certificate does not match the expected. 
main error: TLS session handshake error

When i use the lazyman kodi addon i dont seem to be running into issues. This on my end or is something messed up in the playlist?

Hoping to get setup for puck drop tommorow

**Comment by tarkah** [comment]
VLC is SUPER unreliable for directly playing the m3u8 links due to certificate issues. `lazystream` has a `play` command that will pass the stream to VLC directly with bypassing cert validation and this should work (you need to install https://streamlink.github.io/install.html and make sure it's in  your PATH).

Then you can... `lazystream --date 20200201 --quality 720p60 play select`, select the game, and it should open in VLC and play properly. Another option is to use the record command, it'll download the entire file (I max out my bandwidth downloading), then open it in VLC directly. Record also requires streamlink be installed.

Hope this helps! Let me know if you have any questions

**Comment by tarkah** [comment]
Another option is to install an hls playback extension, like https://addons.mozilla.org/en-US/firefox/addon/hls-js-playback/ for firefox, and open the m3u8 file in your browser. You'll need to make sure to first open the https://mf.svc.nhl.com:443/ws/media/mf/v2.3/key/silk/mediaid/71007003/kid/70290456 link in your browser FIRST and accept the certificate, then load the m3u8 url 
and it should playback in your browser via that extension.

**Comment by Evilmnkey** [comment]
Also tried with MPV and it would not open. Thanks for the info, ill wait and see what happens tomorrow. Just dont get why it stopped working in tivimate also. Could the expired cert on https://mf.svc.nhl.com have anything to do with it?

**Comment by tarkah** [comment]
The games from that date are working fine for me, so it's 99% a cert validation issue on your end. Please try to test with the `play` or `record` command with streamlink installed. If that doesn't work, then I can help investigate further.

**Comment by Evilmnkey** [comment]
Well after clearing the cache and reinstall the mx player on my shield it has started to work
Unsure what did but its working, Thanks for the quick  replys
ready for puck drop!
