### ISSUE TITLE
URL returns "Not available yet"

### ISSUE THREAD

**Issue by avenraw** [tarkah/lazystream#75]
Hello,
I understand this is only implicitly related to lazystream; any help is appreciated but not expected.

I am unable to use the URL to view streams. Plugging the URL into my browser yields "Not available yet" even when the game is playing and readily accessible via LazyMan on Windows.

![query](https://user-images.githubusercontent.com/85044089/120089222-434b5480-c0c6-11eb-9456-88ba94b1bb61.png)

My hosts file is properly edited. However, I am unable to open streams via LazyMan on Linux either (Pop!_OS LTS), receiving the "Failed to create decryptor" error (See #54 ).

Again, I apologize for the tangential relevance. Thanks for all your work.

EDIT: I guess I'm wondering if anyone can enlighten me on what exactly the process is once this URL is acquired, in terms of hosts/proxies/etc., because I don't really understand it.

**Comment by tarkah** [comment]
What game is working on LazyMan but is showing "Not Available"? LazyMan should be grabbing links from that same place so if it's working there, the link should be available...

The "Not Available" is where the game links are hosted and will show up once the games are live. If you use `--resolve` it'll give you the actual link (if it's available). The proxying only comes into play once a link is available, and the hls stream tries to fetch the decryption key. That's where the hosts file updates come in, because it'll now fetch the key from the proxied server (which works without authentication), vs the official servers.

**Comment by avenraw** [comment]
I've spent hours on this and the issue is just that I have the CDN as "aks" rather than "akc" (to be clear, I was generating the URL myself; your program is how I figured this out).

I managed to get things working. I appreciate you explaining a little bit more about how things are working under the hood. Cheers!
